#!/usr/bin/env bash
#
# check all shell scripts

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

readonly REPO_BASE="$(pwd -P)"
source "${REPO_BASE}/setup/utils.sh"

check_shell_scripts() {
  local cmd msg

  # The linter will ignore the following shellcheck errors:
  #   SC1090: Can't follow non-constant source
  #   SC2103: Use a ( subshell ) to avoid having to cd back
  #   SC2034: Foo appears unused.
  #   SC2164: Use cd ... || exit in case cd fails
  # "set -euo pipefail" will exit immediately if something wrong here
  cmd="find ${REPO_BASE}/setup/* test/shell_linter -type f -exec \
        shellcheck -e SC1090 \
                   -e SC2103 \
                   -e SC2034 \
                   -e SC2164 \
                   {} + 1>&2"
  msg="shellcheck all shell scripts"
  do_it "${cmd}" "${msg}"
}

main() {
  echo -e "\n== check shell scripts ==\n"
  check_shell_scripts
}

main
