#!/usr/bin/env bash
#
# clean dotfiles, which remove symlinks which link to dotfile in repository.

# live in strict mode
set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd ..

readonly REPO_BASE="${PWD}"
source "${REPO_BASE}/setup/util.sh"

clean_dotfiles() {
	declare -a dotfiles=(
		"${REPO_BASE}/tmux/tmux.conf"
		"${REPO_BASE}/vim/vimrc"
	)

	local src_file dest_file msg
	for file in "${dotfiles[@]}"; do
		src_file="${file}"
		dest_file="${HOME}/.$(basename "${src_file}")"
		msg="remove ${dest_file}\n"

		if [[ -e "${dest_file}" ]] \
			&& [[ "$(readlink -f "${dest_file}")" == "${src_file}" ]]; then
			
			rm -rf "${dest_file}"; success "${msg}"
		fi
	done
}

main() {
	info "\n== clean dotfiles ==\n\n"
	clean_dotfiles
	info "\n"
}

main

# vim: set filetype=sh :
