#!/usr/bin/env bash
#
# install dotfiles, which make symlink for dotfile.

# live in strict mode
set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd ..

readonly REPO_BASE="${PWD}"
source "${REPO_BASE}/setup/util.sh"

install_dotfiles() {
	declare -a dotfiles=(
		"${REPO_BASE}/tmux/tmux.conf"
		"${REPO_BASE}/vim/vimrc"
	)

	local src_file dest_file
	for file in "${dotfiles[@]}"; do
		src_file="${file}"
		dest_file="${HOME}/.$(basename "${src_file}")"

		mk_link "${src_file}" "${dest_file}"
	done
}

main() {
	info "\n== dotfiles ==\n\n"
	install_dotfiles
	info "\n"
}

main

# vim: set filetype=sh :
