#!/usr/bin/env bash
#
# setup i3wm based on i3-gaps branch

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

readonly REPO_BASE="$(pwd -P)"
source "${REPO_BASE}/setup/utils.sh"

install_wallpaper() {
  local src_file dest_file

  src_file="${REPO_BASE}/.wallpaper.png"
  dest_file="${HOME}/Pictures/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"
}

install_required_app() {
  # wallpaper
  sudo pacman -S feh --noconfirm
  # monitor settings
  sudo pacman -S arandr --noconfirm
  # window layout style
  sudo pacman -S lxappearance --noconfirm
  # file manager
  sudo pacman -S caja --noconfirm
  # dmenu run
  sudo pacman -S rofi --noconfirm
  # mate terminal
  sudo pacman -S mate-terminal --noconfirm
  # light for laptop fn
  sudo pacman -S light --noconfirm
  # audio control
  sudo pacman -S pulseaudio alsa-utils --noconfirm
  # i3wm related
  sudo pacman -S i3lock xorg-xmodmap engrampa mate-utils ttf-font-awesome --noconfirm
  # fcitx input
  sudo pacman -S fcitx-im fcitx-configtool --noconfirm
}

install_xresource_conf() {
  local src_file dest_file

  # for fcixt input and system enviroment
  src_file="${REPO_BASE}/.xprofile"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  # for urxvt terminal
  src_file="${REPO_BASE}/.Xresources"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  # for xinitrc for fonts
  src_file="${REPO_BASE}/.xinitrc"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  # remapping caps to control
  src_file="${REPO_BASE}/.Xmodmap"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"
}

install_i3wm_conf() {
  local src_file dest_file

  mkdir -p "${HOME}/.config/i3/"

  src_file="${REPO_BASE}/i3/status.conf"
  dest_file="${HOME}/.config/i3/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  src_file="${REPO_BASE}/i3/config"
  dest_file="${HOME}/.config/i3/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"
}

main() {
  echo -e "\n== setup i3wm ==\n"
  install_required_app
  install_xresource_conf
  install_wallpaper
  install_i3wm_conf
}

main
