#!/usr/bin/env bash
#
# setup i3wm based on i3-gaps branch

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

readonly REPO_BASE="$(pwd -P)"
source "${REPO_BASE}/setup/utils.sh"

install_wallpaper() {
  local src_file dest_file

  src_file="${REPO_BASE}/.wallpaper.png"
  dest_file="${HOME}/Pictures/$(basename "${src_file}")"

  mkdir -p "$HOME/Pictures"
  mk_link "${src_file}" "${dest_file}"
}

install_required_app() {
  # wallpaper
  sudo apt install feh -y
  # monitor settings
  sudo apt install arandr -y
  # window layout style
  sudo apt install lxappearance -y
  # file manager
  sudo apt install caja -y
  # dmenu run
  sudo apt install rofi -y
  # mate terminal and konsole
  sudo apt install mate-terminal konsole -y
  # light for laptop fn
  sudo apt install light -y
  # audio control
  sudo apt install pulseaudio alsa-utils pulseaudio-utils -y
  # i3wm related
  sudo apt install i3lock engrampa mate-utils fonts-font-awesome -y
  # fcitx input
  sudo apt install fcitx fcitx-googlepinyin -y
  # Chinese fonts
  sudo apt install ttf-wqy-microhei ttf-wqy-zenhei -y
  # firmware
  sudo apt install -y \
    firmware-iwlwifi \
    firmware-misc-nonfree \
    firmware-realtek \
    firmware-sof-signed
  # network manager
  sudo apt install network-manager-gnome -y
  # bluetools
  #
  # NOTE:
  # 1. update /etc/bluetooth/main.conf with 'ControllerMode = bredr'
  # 2. update bluetoothd systemd service with the config file
  sudo apt install blueman -y
  # devtools
  sudo apt-get install -y \
    wget \
    curl \
    unzip \
    zip \
    tree \
    tar \
    silversearcher-ag \
    jq \
    zsh \
    vim \
    neovim \
    tmux \
    git \
    gcc \
    cmake \
    make \
    lsof \
    build-essential \
    libelf-dev \
    clang \
    linux-headers-$(uname -r) \
    gcc-multilib
}

install_xresource_conf() {
  local src_file dest_file

  # for fcixt input and system enviroment
  src_file="${REPO_BASE}/.xprofile"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  # for urxvt terminal
  src_file="${REPO_BASE}/.Xresources"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  # for xinitrc for fonts
  src_file="${REPO_BASE}/.xinitrc"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  # remapping caps to control
  src_file="${REPO_BASE}/.Xmodmap"
  dest_file="${HOME}/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"
}

install_i3wm_conf() {
  local src_file dest_file

  mkdir -p "${HOME}/.config/i3/"

  src_file="${REPO_BASE}/i3/status.conf"
  dest_file="${HOME}/.config/i3/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"

  src_file="${REPO_BASE}/i3/config"
  dest_file="${HOME}/.config/i3/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"
}

install_fonts() {
  local -a rcs
  local src_file dest_file

  rcs=(
    "Font Awesome 5 Brands-Regular-400.otf"
    "Font Awesome 5 Free-Regular-400.otf"
    "Font Awesome 5 Free-Solid-900.otf"
    "MesloLGS NF Bold.ttf"
    "MesloLGS NF Regular.ttf"
  )

  mkdir -p "$HOME/.fonts"

  for file in "${rcs[@]}"; do
    src_file="${REPO_BASE}/i3/fonts/${file}"
    dest_file="${HOME}/.fonts/$(basename "${src_file}")"
    mk_link "${src_file}" "${dest_file}"
  done
}

main() {
  echo -e "\n== setup i3wm ==\n"
  install_required_app
  install_xresource_conf
  install_wallpaper
  install_i3wm_conf
  install_fonts
}

main
