#!/usr/bin/env bash
#
# setup bash
# All rc files will be located in ${HOME}/.bashrc.d directory.

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

readonly REPO_BASE="$(pwd -P)"
source "${REPO_BASE}/setup/utils.sh"

setup_bashrc_d() {
  local cmd msg

  cmd="mkdir -p ${HOME}/.bashrc.d"
  msg="create directory ${HOME}/.bashrc.d"
  do_it "${cmd}" "${msg}"
}

install_bashrc_files() {
  local -a rcs
  local src_file dest_file

  rcs=(
    "bashrc"
    "bash_prompts"
  )

  for file in "${rcs[@]}"; do
    src_file="${REPO_BASE}/bash/${file}"
    dest_file="${HOME}/.bashrc.d/${file}"
    mk_link "${src_file}" "${dest_file}"
  done
}

update_user_bashrc() {
  local line

  # insert line into ~/.bashrc
  line="[[ -f ${HOME}/.bashrc.d/bashrc ]] && source ${HOME}/.bashrc.d/bashrc"
  insert_line "${HOME}/.bashrc" "${line}"
}

main() {
  echo -e "\n==setup bash==\n"
  setup_bashrc_d
  install_bashrc_files
  update_user_bashrc
}

main
