#!/usr/bin/env bash
#
# setup nvim

cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..

readonly REPO_BASE="$(pwd -P)"
source "${REPO_BASE}/setup/utils.sh"

create_config_dir() {
  mkdir -p "${HOME}/.config/nvim/"
}

install_nvimrc() {
  local src_file dest_file

  src_file="${REPO_BASE}/nvim/init.vim"
  dest_file="${HOME}/.config/nvim/$(basename "${src_file}")"
  mk_link "${src_file}" "${dest_file}"
}

install_nvim_plug() {
  local cmd msg

  cmd="curl -fLo ${HOME}/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  msg="install vim-plug plugin"
  do_it "${cmd}" "${msg}"
}

update_plugins() {
  local cmd msg

  cmd="nvim +PlugInstall +qall < $(tty) > /dev/null"
  msg="update nvim plugins [will take several minutes...]"
  do_it "${cmd}" "${msg}"
}

main() {
  echo -e "\n== setup nvim ==\n"
  create_config_dir
  install_nvimrc
  install_nvim_plug
  update_plugins
}

main
