#!/usr/bin/env bash
#
# Customize bash variables
#
# Note: Don't set errexit flag in this script.

# change default editor to vim
export EDITOR=vim

# ignore commands that start with spaces and duplicates and remove duplicates
export HISTCONTROL=ignorespace:ignoredups:erasedups

# change the maximum number of lines of history to 4k
export HISTSIZE=$((1 << 12))

# change the maxinum file size of history to 64k
export HISTFILESIZE=$((1 << 16))

# keep the times of the commands in history
export HISTTIMEFORMAT='%F %T  '

# use UTF-8 encoding
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# How to hack PS1:
# from https://www.gnu.org/software/bash/manual/bashref.html
#   If set PROMPT_COMMAND, the value is interpreted as a command to execute
#   before the printing of each primary prompt ($PS1).
export PROMPT_COMMAND="__customize_prompts"
